#define TOKEN_PLUS                            1
#define TOKEN_MINUS                           2
#define TOKEN_STAR                            3
#define TOKEN_SLASH                           4
#define TOKEN_EQ                              5
#define TOKEN_LT                              6
#define TOKEN_GT                              7
#define TOKEN_COMMA                           8
#define TOKEN_WORD                            9
#define TOKEN_STRING                         10
#define TOKEN_NUMBER                         11
#define TOKEN_SUBCLASS                       12
#define TOKEN_COLON                          13
#define TOKEN_LSQBRACK                       14
#define TOKEN_RSQBRACK                       15
#define TOKEN_EXTEND                         16
#define TOKEN_BAR                            17
#define TOKEN_KEYWORD                        18
#define TOKEN_STOP                           19
#define TOKEN_COMMENT                        20
#define TOKEN_RETURN                         21
#define TOKEN_SEMICOLON                      22
#define TOKEN_SYMBOL                         23
#define TOKEN_FLOATNUMBER                    24
#define TOKEN_AT                             25
#define TOKEN_LPAREN                         26
#define TOKEN_RPAREN                         27
#define TOKEN_LBRACE                         28
#define TOKEN_RBRACE                         29
