
#ifndef OBJC_MALLOC_TYPES_H
#define OBJC_MALLOC_TYPES_H

MALLOC_DECLARE(M_AUTORELEASE_POOL_TYPE);
MALLOC_DECLARE(M_BLOCKS_TYPE);
MALLOC_DECLARE(M_BUFFER_TYPE);
MALLOC_DECLARE(M_CATEGORY_LIST_TYPE);
MALLOC_DECLARE(M_CLASS_TYPE);
MALLOC_DECLARE(M_CLASS_EXTRA_TYPE);
MALLOC_DECLARE(M_CLASS_MAP_TYPE);
MALLOC_DECLARE(M_ENCODING_TYPE);
MALLOC_DECLARE(M_EXCEPTION_TYPE);
MALLOC_DECLARE(M_FAKE_CLASS_TYPE);
MALLOC_DECLARE(M_IVAR_TYPE);
MALLOC_DECLARE(M_IVAR_LIST_TYPE);
MALLOC_DECLARE(M_LOAD_MSG_MAP_TYPE);
MALLOC_DECLARE(M_METHOD_TYPE);
MALLOC_DECLARE(M_METHOD_DESC_LIST_TYPE);
MALLOC_DECLARE(M_METHOD_LIST_TYPE);
MALLOC_DECLARE(M_OBJECT_TYPE);
MALLOC_DECLARE(M_PROPERTY_TYPE);
MALLOC_DECLARE(M_PROPERTY_LIST_TYPE);
MALLOC_DECLARE(M_PROTOCOL_TYPE);
MALLOC_DECLARE(M_PROTOCOL_LIST_TYPE);
MALLOC_DECLARE(M_PROTOCOL_MAP_TYPE);
MALLOC_DECLARE(M_REFLIST_TYPE);
MALLOC_DECLARE(M_SELECTOR_MAP_TYPE);
MALLOC_DECLARE(M_SELECTOR_NAME_TYPE);
MALLOC_DECLARE(M_SELECTOR_TYPE);
MALLOC_DECLARE(M_SLOT_POOL_TYPE);
MALLOC_DECLARE(M_SPARSE_ARRAY_TYPE);
MALLOC_DECLARE(M_UTILITIES_TYPE);


#endif /* OBJC_MALLOC_TYPES_H */
